appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: hFqdtQrjeaeCWS1pCDudXbBWbL8T/v3AiX9xc2ykGJaoedntvazMuWSlBuGDP6PaL4klBgikeoXa1XG0cUeUi5pWRidcY69jHx3i9ql4CGPqgy6sU4VGP3hTpW9WwlxAhZZNgfYPnI1DBq2ALXGLvXmm6dl15qvXxoovYh3p35sTRzt6TqCBDs2Vc2iyPay7wVzazTsk1m2P8TF7nCjpMk1bzk1LIZJ8L+d3/jx1aW9aHG3y3VGRTAKMbNBa9Yn5q62snzBgBsnpkkc9sLSXrrZmxA4UBybuWvxLBmW3QxnBn5NCRICgSFuQcCifozyqfQtJXeS9KJ+3ixVwrMzNhvduHz1/BjiaFg3ACpFRFrW45iTjFU0CufVKNkHGmvxIGNlerMibAgGj2NpLP88XuoxDDAYcP+091JC2aGq6yKYoi1houKU7q/BJAcEkwsC6Bl3Fwc768GYnMWcOJJuOmMlpcLqJ0nlyq65YLwrhR25lh8iY4srToH5LoS2pONp+F73bXxxPGHlJgrnYXA0gQulHbqNEqHTTZYIwWonKF/kHH5mF4Bl5CFrp8gfr7NvHBL0BtixjLQmg4tGqA4++xk1GSKjeGkKlE0HxsXZUBQuX68LniXmixT78B3JlK/OPWXQ0wrMEmnfHpwk8wlsqUhPHVarI9FVMZOoMOBkBjB0=
conda_forge_output_validation: true
